#+TITLE: A litterate programming approach to customize emacs
#+AUTHOR: Alex Patry
#+EMAIL: alex@nlpfu.com

* Introduction

This file is used to customize emacs to my needs. The pattern is to
add one section per type of configuration and then make sure that
all modules and configuration are defined in it.

The organization of this file is greatly inspired from Joost
Diepenmaat and the code he shared at
https://github.com/joodie/emacs-literal-config.

If you want to use this structure yourself, the easiest way to get
started is probably to clone this repository and move it at
=~/.emacs.d=. Make sure that no file is named =~/.emacs= as it would
be used instead of =~/.emacs.d/init.el= when emacs is starting.

* Prologue

Before we start actually configuring our environment, let's define
some utilities that will help us get organized:

#+BEGIN_SRC emacs-lisp
  (require 'package)

  (let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
		      (not (gnutls-available-p))))
	 (proto (if no-ssl "http" "https")))
    (when no-ssl
      (warn "\
  Your version of Emacs does not support SSL connections,
  which is unsafe because it allows man-in-the-middle attacks.
  There are two things you can do about this warning:
  1. Install an Emacs version that does support SSL and be safe.
  2. Remove this warning from your init file so you won't see it again."))

    ;; Add all the package repositories that we want to use.
    (add-to-list 'package-archives
		 (cons "melpa" (concat proto "://melpa.org/packages/")) t))

  ;; Initialize the package module, this must be after 'package-archives
  ;; has been set
  (package-initialize)

  ;; Reloading the list of packages takes time, we will do it at most
  ;; once. This variable will be true if the list has already be
  ;; reloaded.
  (setq my/package-refreshed nil)

  ;; Install a package if it is not already installed.
  (defun my/install (package)
    (unless (package-installed-p package)
      (unless my/package-refreshed
	(package-refresh-contents)
	(setq my/package-refreshed t))
      (package-install package)))
#+END_SRC

#+RESULTS:
: my/install

* Use Package

At first, I was using =my/install= for all my packages. I decided to
test drive =use-package= and see how it could make things
better. Before migrating to it, my startup time was:

#+BEGIN_VERBATIM
time emacs -l .emacs.d/init.el  -batch --eval '(message "Hello, world!")'
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Tangled 35 code blocks from emacs.org
Loading /home/alex/.emacs.d/emacs.el (source)...
Loading /home/alex/.emacs.d/custom.el (source)...
Loaded /home/alex/.emacs.d/emacs.el
Hello, world!
emacs -l .emacs.d/init.el -batch --eval '(message "Hello, world!")'  1.12s user 0.06s system 99% cpu 1.188 total
#+END_VERBATIM

After the migration, it was:

#+BEGIN_VERBATIM
time emacs -l .emacs.d/init.el  -batch --eval '(message "Hello, world!")'
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /home/alex/.emacs.d/emacs.el (source)...
Loading /home/alex/.emacs.d/custom.el (source)...
Loaded ~/.emacs.d/emacs.el
Hello, world!
emacs -l .emacs.d/init.el -batch --eval '(message "Hello, world!")'  1.09s user 0.03s system 99% cpu 1.124 total
#+END_VERBATIM

#+BEGIN_SRC emacs-lisp
(my/install 'use-package)
#+END_SRC

* Startup configuration

By default, emacs show a welcome screen. While it can be useful the
first time we start emacs, it gets old very fast. Let's disable it:

#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-screen t)
#+END_SRC

Also, emacs comes with a toolbar that is next to useless, let's
reclaim back this space:

#+BEGIN_SRC emacs-lisp
  (if (display-graphic-p)
    (tool-bar-mode -1))
#+END_SRC

* Custom commands

#+BEGIN_SRC emacs-lisp :results silent output
  (defun dot-emacs ()
    "Shortcut to open this file. I often tweak my emacs config,
  this short cut makes it easier to get here."
    (interactive)
    (find-file "~/.emacs.d/emacs.org"))
#+END_SRC

* Flycheck

Flycheck checks the syntax in many programming language and add visual
markers when it detects an error. We want to enable it by default:

#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :config (global-flycheck-mode)
    :ensure t)
#+END_SRC

More info at https://www.flycheck.org/en/latest/

* Backups

By default, emacs save backup files in the same directory as the files
we are editing. Instead of adding files everywhere, let's use a
dedicated directory for these backups:

#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist `(("." . "~/.emacs.d/backups/")))
#+END_SRC

Let's also have more backup per file as suggested [[http://stackoverflow.com/a/151946][here]]:

#+BEGIN_SRC emacs-lisp
  (setq delete-old-versions t
    kept-new-versions 6
    kept-old-versions 2
    version-control t)
#+END_SRC

* Color theme

I will give [[https://github.com/hlissner/emacs-doom-themes#features][doom-themes]] a try:

#+BEGIN_SRC emacs-lisp
  (use-package doom-themes
    :config
    (load-theme 'doom-gruvbox t)
    (doom-themes-org-config)
    :ensure t)
#+END_SRC

* Git

Let's use magit to deal with git command from within emacs:

#+BEGIN_SRC emacs-lisp
  (use-package magit
   :ensure t)
#+END_SRC

We will also add git modification into the [[https://github.com/syohex/emacs-git-gutter][gutter]]:

#+BEGIN_SRC emacs-lisp
  (use-package git-gutter
    :config (global-git-gutter-mode +1)
    :ensure t)
#+END_SRC

* Graphviz

#+BEGIN_SRC emacs-lisp
  (use-package graphviz-dot-mode
    :mode "\\.dot\\'"
    :ensure t)
#+END_SRC

* Groovy

Add support for groovy files:

#+BEGIN_SRC emacs-lisp
  (use-package groovy-mode
    :mode "\\.groovy\\'\\|\\.gradle\\'"
    :ensure t)
#+END_SRC

* Helm

[[https://github.com/emacs-helm/helm/wiki#install][Helm]] is an auto-completion package for emacs. I am not familiar with
it yet, so this config might be suboptimal:

#+BEGIN_SRC emacs-lisp

(use-package helm
  :bind (("M-x" . helm-M-x)
         ("C-x r b" . helm-filtered-bookmarks)
         ("C-x C-f" . helm-find-files))
  :config (helm-mode 1)
  :ensure t)
#+END_SRC

* Markdown

Add support for markdown

#+BEGIN_SRC emacs-lisp
  (use-package markdown-mode
    :mode "\\.md\\'"
    :ensure t)
#+END_SRC

* Nix

Let's add support for nix, a package manager.

#+BEGIN_SRC emacs-lisp :results silent
  (use-package nix-mode
    :mode "\\.nix\\'"
    :ensure t)
#+END_SRC

#+RESULTS:

* Pig

Use [[https://github.com/motus/pig-mode][pig-mode]] with indent of 2:

#+BEGIN_SRC emacs-lisp
  (use-package pig-mode
    :init (setq pig-indent-level 2)
    :mode "\\.pig\\'"
    :ensure t)
#+END_SRC

* Projectile

Use [[https://github.com/bbatsov/projectile][projectile]] to search for files:

#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :init (setq projectile-project-root-files "~/workspace")
    :ensure t)

  (use-package helm-projectile
    :after projectile
    :ensure t)
#+END_SRC

* Javascript

Javascript mode is shipped by default with emacs, we just want to set
its configuration:

#+BEGIN_SRC emacs-lisp
 (setq js-indent-level 2)
#+END_SRC

* Modeline

Let's use [[https://github.com/seagle0128/doom-modeline][doom-modeline]]:

#+BEGIN_SRC emacs-lisp
  ;; run the following only once to install the fonts required by
  ;; doom-modeline. I didn't find an easy way to run this only once ...
  ; (my/install 'all-the-icons)
  ; (require 'all-the-icons)
  ; (all-the-icons-install-fonts)

  (use-package doom-modeline
    :config (doom-modeline-mode 1)
    :ensure t)
#+END_SRC

* Protobuf

#+BEGIN_SRC emacs-lisp
  (use-package protobuf-mode
    :mode "\\.proto\\'"
    :ensure t)
  (my/install 'protobuf-mode)
#+END_SRC

* Thrift

#+BEGIN_SRC emacs-lisp
  (use-package thrift
    :mode "\\.thrift\\'"
    :ensure t)
#+END_SRC

* Python

Let's start by installing modes for python and python documentation:

#+BEGIN_SRC emacs-lisp
  (use-package python
    :config
      (custom-set-variables
        '(python-indent-guess-indent-offset nil)
	'(python-indent-offset 2))
	(when (executable-find "ipython")
	  (setq python-shell-interpreter "ipython"
                python-shell-interpreter-args "-i")))

  (use-package flycheck-pyflakes
    :ensure t)

  (use-package python-docstring
    :hook ((python-mode . python-docstring-mode))
    :ensure t)
#+END_SRC
* Scala

Add support for scala:

#+BEGIN_SRC emacs-lisp
  (use-package scala-mode
    :mode "\\.scala\\'"
    :ensure t)
#+END_SRC

* Sparql

Add support for sparql:

#+BEGIN_SRC emacs-lisp :results silent output
  (use-package sparql-mode
    :mode "\\.sparql\\'"
    :ensure t)
#+END_SRC

* TeX

#+BEGIN_SRC emacs-lisp
  (use-package auctex
    :mode "\\.tex\\'"
    :ensure t)
  (my/install 'auctex)
#+END_SRC

* XML

XML is still useful sometimes, let's set us up for these cases:

#+BEGIN_SRC emacs-lisp
  (use-package auto-complete-nxml
    :mode "\\.xml\\'"
    :init
    ;; Keystroke to popup help about something at point.
    (setq auto-complete-nxml-popup-help-key "C-:")
    ;; Keystroke to toggle on/off automatic completion.
    (setq auto-complete-nxml-toggle-automatic-key "C-c C-t")
    :ensure t)

  (use-package rnc-mode
    :mode "\\.rnc\\'"
    :ensure t)
#+END_SRC

* Whitespaces

Nobody likes trailing whitespaces, let's just remove them:

#+BEGIN_SRC emacs-lisp
(add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC

* Org-mode

#+BEGIN_SRC emacs-lisp
  (use-package org
    :bind (("C-c l" . org-store-link)
           ("C-c c" . org-capture)
           ("C-c a" . org-agenda)
           ("C-c b" . org-iswitchb)
           ("C-c C-w" . org-refile)
           ("C-c j" . org-clock-goto)
           ("C-c C-x C-o" . org-clock-out))

    :config
      (setq org-todo-keywords '((sequence "TODO" "IN-PROGRESS" "BLOCKED" "|" "DONE" "DELEGATED")))

      ;; Capture timestamp when tasks are done
      (setq org-log-done t)

      ;; Make sure we don't kill the whole subtree when killing folded hearders
      (setq org-ctrl-k-protect-subtree t)

      ;; Align tags in the headline
      (setq org-tags-column t)

      ;; Prettify code blocks
      (setq org-src-fontify-natively t)
    :init
      (org-babel-do-load-languages 'org-babel-load-languages
        '((emacs-lisp t)
	  (python . t)
	  (shell . t)
	  (sparql . t))))
#+END_SRC

** ox-hugo

[[https://ox-hugo.scripter.co/][ox-hugo]] is an org-mode exporter allowing to blog with the [[https://gohugo.io][Hugo]]
platform in org-mode.

#+BEGIN_SRC emacs-lisp :results silent
  (use-package ox-hugo
    :after ox
    :ensure t)
#+END_SRC

** Appearance

First, let's start by configuring the appearance of top level items:

#+BEGIN_SRC emacs-lisp
  ;; let's replace the stars with actual bullets
  (use-package org-bullets
    :hook (org-mode . org-bullets-mode)
    :ensure t)
#+END_SRC

Make sure to run =M-x all-the-icons-install-fonts= at least once on
your system if the icons do not render well.

* Epilogue

** Custom values
Let's store custom values in a dedicated file:

#+BEGIN_SRC emacs-lisp
 (setq custom-file "~/.emacs.d/custom.el")
 (load custom-file)
#+END_SRC
