;; DO NOT EDIT THIS FILE, USE emacs.org INSTEAD.

;; Run the elisp code in our main configuration file

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(org-babel-load-file "~/.emacs.d/emacs.org")
